version: '3.8'

services:
  telegram-bot:
    build:
      context: ./bot
    restart: always
    env_file:
      - ./bot/.env
    volumes:
      - ./bot:/app
    

  fastapi:
    build: ./main
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./main/.env
    volumes:
      - ./main:/app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  backup:
    build:
      context: ./backup
    volumes:
      - ./bot:/app/bot
      - ./main:/app/main
      - ./backup:/app/backup    
      - ./backups:/app/backups    

networks:
  web:
  internal:
    internal: true