version: '3.8'

services:
  # nginx:
  #   image: nginx:1.25-alpine
  #   restart: always
  #   ports:
  #     - "443:443"                # наружу – только 443
  #   volumes:
  #     - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/nginx/certs:ro
  #   depends_on: [fastapi]
  #   networks: [web, internal]
    
  telegram-bot:
    build:
      context: ./bot
    restart: always
    env_file:
      - ./bot/.env
    volumes:
      - ./bot:/app
    

  fastapi:
    build: ./main
    # expose: ["8080"]             # НЕ ports
    # networks: [internal]
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./main/.env
    volumes:
      - ./main:/app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  backup:
    build:
      context: ./backup
    volumes:
      - ./bot:/app/bot
      - ./main:/app/main
      - ./backup:/app/backup    
      - ./backups:/app/backups    

networks:
  web:
  internal:
    internal: true