FROM python:3.12.6-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем скрипт резервного копирования
COPY backup.sh .

# Создаем папку для резервных копий
RUN mkdir -p /app/backups

# Делаем скрипт исполняемым
RUN chmod +x backup.sh

# Запускаем скрипт резервного копирования
CMD ["./backup.sh"]